# Generated by Django 5.2.5 on 2025-08-25 10:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0002_quote_dislikes_quote_likes_alter_source_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='source',
            field=models.ForeignKey(help_text='The source of the quote.', on_delete=django.db.models.deletion.CASCADE, to='quotes.source'),
        ),
    ]
